export const getMagicLinkTemplate = (actionLink: string, userName?: string) => {
  const brandColor = '#2563eb';
  return `<!DOCTYPE html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Tu acceso a GoTogether</title></head><body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f9fafb;margin:0;padding:0"><div style="max-width:600px;margin:40px auto;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 12px rgba(0,0,0,.05)"><div style="padding:40px 40px 20px;text-align:center"><p style="font-size:28px;font-weight:800;color:${brandColor};margin:0">GoTogether</p></div><div style="padding:0 40px 40px;color:#374151;line-height:1.6"><h1 style="font-size:24px;font-weight:700;color:#111827;margin-bottom:16px">Tu enlace de acceso</h1><p>Hola${userName ? ` ${userName}` : ''},</p><p>Haz clic abajo para acceder de forma segura.</p><div style="margin:32px 0;text-align:center"><a href="${actionLink}" style="background:${brandColor};color:#fff;padding:16px 32px;border-radius:12px;font-weight:600;text-decoration:none;display:inline-block;font-size:16px;box-shadow:0 4px 6px -1px rgba(37,99,235,.2)">Entrar en GoTogether</a></div><p>Si no has solicitado este correo, ignóralo.</p></div><div style="padding:32px 40px;background:#f3f4f6;color:#6b7280;font-size:14px;text-align:center"><p>&copy; ${new Date().getFullYear()} GoTogether</p></div></div></body></html>`;
};

export function getSupervisionInviteTemplate(params: {
  supervisorName: string;
  clientName: string;
  acceptUrl: string;
}) {
  const brandColor = '#2563eb';
  return `<!DOCTYPE html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Invitación de supervisión - GoTogether</title></head><body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f9fafb;margin:0;padding:0"><div style="max-width:600px;margin:40px auto;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 12px rgba(0,0,0,.05)"><div style="padding:40px 40px 20px;text-align:center;background:linear-gradient(135deg,${brandColor} 0%,#3b82f6 100%)"><p style="font-size:28px;font-weight:800;color:#fff;margin:0">GoTogether</p></div><div style="padding:0 40px 40px;color:#374151;line-height:1.6"><h1 style="font-size:24px;font-weight:700;color:#111827;margin-bottom:16px">Invitación de supervisión</h1><p>Hola ${params.clientName},</p><p><strong>${params.supervisorName}</strong> te ha invitado a conectar en GoTogether como tu supervisor. Esto le permitirá ayudarte a gestionar tus reservas y acompañamientos.</p><div style="background:#f8fafc;border-radius:12px;padding:24px;margin:24px 0;border:1px solid #e2e8f0"><p style="font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:.05em;color:#64748b;margin:0 0 4px">Supervisor</p><p style="font-size:18px;font-weight:600;color:#0f172a;margin:0">${params.supervisorName}</p></div><p>Haz clic en el botón de abajo para aceptar la invitación y comenzar.</p><div style="margin:32px 0;text-align:center"><a href="${params.acceptUrl}" style="background:${brandColor};color:#fff;padding:16px 32px;border-radius:12px;font-weight:600;text-decoration:none;display:inline-block;font-size:16px;box-shadow:0 4px 6px -1px rgba(37,99,235,.2)">Aceptar invitación</a></div><p style="font-size:14px;color:#6b7280">Si no conoces a esta persona o no deseas conectar, simplemente ignora este mensaje.</p></div><div style="padding:32px 40px;background:#f3f4f6;color:#6b7280;font-size:14px;text-align:center"><p>&copy; ${new Date().getFullYear()} GoTogether</p></div></div></body></html>`;
}
