export const routes = {
  info: '/info',
  nosotros: '/nosotros',
  contacto: '/contacto',
  primerosPasos: '/primeros-pasos',
  solicitud: '/solicitud',
  perfil: '/perfil',
  explorar: '/explorar',
  explorarCompanion: (id: string) => `/explorar/${id}`,
  reservas: '/reservas',
  panel: '/panel',
  coordinacion: '/coordinacion',
  valoracion: '/valoracion',
  login: '/auth/login',
  onboarding: '/onboarding',
  onboardingClient: '/onboarding/register/client',
  onboardingCompanion: '/onboarding/register/companion',
  admin: '/admin',
  historial: '/historial',
} as const;
