export const routes = {
  solicitud: '/solicitud',
  perfil: '/perfil',
  explorar: '/explorar',
  explorarCompanion: (id: string) => `/explorar/${id}`,
  reservas: '/reservas',
  panel: '/panel',
  coordinacion: '/coordinacion',
  valoracion: '/valoracion',
  login: '/auth/login',
  onboarding: '/onboarding',
  onboardingClient: '/onboarding/register/client',
  onboardingCompanion: '/onboarding/register/companion',
  onboardingSupervisor: '/onboarding/supervisor',
  supervision: '/supervision',
  supervisionAccept: '/supervision/accept',
} as const;
